In [2]:
import torch
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [3]:
print("PyTorch version: ", torch.__version__)
print("CUDA version: ", torch.version.cuda)
print(torch.cuda.get_device_name(0))

PyTorch version:  2.5.1
CUDA version:  12.1
NVIDIA GeForce GTX 1650 SUPER


## Intoduction a Tensors

### Creating tensors

In [ ]:
# scaler tensor
scaler = torch.tensor(7)
print(scaler)

tensor(7)


In [ ]:
# dimension of scaler tensor is 0
scaler.ndim

0

In [ ]:
# Get the python integer from scaler tensor
scaler.item()

7

In [15]:
# vector tensor
vector = torch.tensor([10, 20, 30])
print(vector)
print(vector.ndim)
vector.shape

tensor([10, 20, 30])
1


torch.Size([3])

In [17]:
# MATRIIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


In [19]:
MATRIX[0][1]

tensor(8)

In [29]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3,6],
                        [3,6,9,7],
                        [2,4,5,9]],[[1,2,3,6],
                                    [3,6,9,7],
                                    [2,4,5,9]]])
TENSOR

tensor([[[1, 2, 3, 6],
         [3, 6, 9, 7],
         [2, 4, 5, 9]],

        [[1, 2, 3, 6],
         [3, 6, 9, 7],
         [2, 4, 5, 9]]])

In [30]:
TENSOR.ndim

3

In [31]:
TENSOR.shape

torch.Size([2, 3, 4])

### Random Tensors

In [33]:
# Create a random tensor of size (3,4)

X = torch.rand(3,4)
X

tensor([[0.0401, 0.5011, 0.2000, 0.9966],
        [0.7699, 0.0773, 0.6837, 0.8853],
        [0.7491, 0.9968, 0.6430, 0.0394]])

In [ ]:
X.ndim # Because it has 2 square bracets

2

In [35]:
# Create a random tensor with similar shape of an image tensor
random_image_tensor = torch.rand(224,224,3) # height, width, color_channels [R,G,B]
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Creating a range of tensors and tensors-like

In [41]:
# torch.range() is deprecated in PyTorch 0.4.0. You should use torch.arange() instead.

one_to_ten = torch.arange(1,11)
# with args
one_to_nine = torch.arange(start=1, end=10, step=1)
one_to_nine

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
# Creatng tensor like
nine_zeros = torch.zeros_like(input=one_to_nine)
nine_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

### Manupulating tensor (tensor operations)

Tensor operation includes
* Addition
* Subtraction
* Multiplication (element wise)
* Division
* Matrix multiplication

In [45]:
# Create a tensor
tensor = torch.tensor([1,2,3,4,5])
tensor + 12

tensor([13, 14, 15, 16, 17])

In [47]:
# Built in PyTorch functions
torch.add(tensor, 12)
print(tensor)
print(tensor.mul(10))

tensor([1, 2, 3, 4, 5])
tensor([10, 20, 30, 40, 50])


In [53]:
%%time
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3, 4, 5]) * tensor([1, 2, 3, 4, 5])
Equals: tensor([ 1,  4,  9, 16, 25])
CPU times: user 0 ns, sys: 1.71 ms, total: 1.71 ms
Wall time: 1.29 ms


In [52]:
%%time
# Matrix multiplication (dot product)
torch.matmul(tensor, tensor)

CPU times: user 189 μs, sys: 42 μs, total: 231 μs
Wall time: 185 μs


tensor(55)

## Reshaping, stacking, squeezing, and unsqueezing tensors

* Reshaping tensors - Changing the shape of a given tensor
* View - Returns a preview of a reshaped tensor without changing the original tensor
* Stack - Stacks a sequence of tensors along a new dimension
* Squeeze - Removes single-dimensional entries from the shape of a tensor
* Unsqueeze - Adds a new dimension to a tensor
* Permute - Changes the order of dimensions of a tensor

## Reprodciblity (trying to take random out of random)

To reduce the randomness in neural networks and Pytorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [9]:
torch.rand(3,3)

tensor([[0.6506, 0.0783, 0.1717],
        [0.4037, 0.2408, 0.3447],
        [0.9506, 0.3938, 0.4759]])

In [10]:
# Some random but reproduciable tensors

# Random seed
RANDOM_SEED = 42 

torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3,4)


torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
